#!/usr/bin/env python
env = SConscript("godot-cpp/SConstruct")
env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")
library = env.SharedLibrary(
    "bin/libteknik_carpathian{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)
env.NoCache(library)
Default(library)
